# config.py

DEFAULT_WATERMARK_SIZE = 40
DEFAULT_WATERMARK_TRANSPARENCY = 100
DEFAULT_WATERMARK_POSITION = "bottom_center"
DEFAULT_FONT_SIZE = 20
DEFAULT_SOFT_EDGE = True
DEFAULT_INCLUDE_DATE = False
DEFAULT_SAME_POSITION = True
